name = input("input name of product: ")
quantity = input("input quantity: ")
amount = input("input amount: ")
full_amount = (int(quantity) * int(amount))
print(quantity + " " + name + ": " + str(full_amount))